
common: &default_settings
  license_key: Settings.new_relic.key
  app_name: LocalVertcoins
  log_level: info


development:
  <<: *default_settings
  app_name: LocalVertcoins (Development)
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: LocalVertcoins (Staging)

production:
  <<: *default_settings
