new_relic:
  key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>

attr_encrypted:
  key: <%= ENV['ATTR_ENCRYPTED_KEY'] %>

google_maps_embed:
  key: <%= ENV['GOOGLE_MAPS_EMBED_API_KEY'] %>

smtp_config:
  user_name: <%= ENV['SMTP_USER_NAME'] %>
  password: <%= ENV['SMTP_PASSWORD'] %>
  address: <%= ENV['SMTP_ADDRESS'] %>
  domain: <%= ENV['SMTP_DOMAIN'] %>
  port: <%= ENV['SMTP_PORT'].to_i %>
  authentication: <%= ENV['SMTP_AUTH'].to_sym %>

default_url:
  host: <%= ENV['URL_HOST'] %>
  port: <%= ENV['URL_PORT'].to_i %>
